import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const dictionary = {
  en: {
    // Admin Console
    adminController: "Admin Controller",
    activeTenants: "Active Tenants",
    expiredAccounts: "Expired Accounts",
    totalRevenue: "Total Revenue",
    manageShops: "Manage Shops",
    analysis: "Analysis",
    shopName: "Shop Name",
    ownerName: "Owner Name",
    username: "Username",
    password: "Password",
    plan: "Plan",
    category: "Category",
    provisionAccount: "Provision Account",
    storeSubscriptions: "Store Subscriptions",
    createStoreAccount: "Create Store Account",
    manageCategories: "Manage Shop Categories",
    addCustomCategory: "Add Custom Category",

    // Navigation & Tabs
    home: "Home",
    billing: "Billing",
    stock: "Stock",
    expenses: "Expenses",
    reports: "Reports",
    logout: "Logout",

    // Merchant Dashboard Metrics
    totalSales: "Total Sales",
    netProfit: "Net Profit",
    itemsSold: "Items Sold",
    customersVisited: "Customers Visited",

    // Common UI Labels & Actions
    quickActions: "Quick Actions",
    recentBills: "Recent Bills",
    addStock: "Add Stock",
    addExpense: "Add Expense",
    billingCheckout: "Billing & Checkout",
    expired: "Expired",
    active: "Active",
    expiresIn: "Expires in",
    viewPricing: "View Pricing & Subscription",
    days: "days",
    day: "day",
    expiredPlanWarning: "Your subscription has expired! Please renew.",
    expirationWarning: "Your plan expires in {days} days!",
    renewNow: "Renew Now",
    recentTransactions: "Recent Transactions",
    paymentMethod: "Payment Method",
    CASH: "Cash",
    UPI: "UPI",
    CARD: "Card",
    cash: "Cash",
    upi: "UPI",
    card: "Card",
    amount: "Amount",
    description: "Description",
    save: "Save",
    cancel: "Cancel",
    search: "Search",
    qty: "Qty",
    price: "Price",
    buyingPrice: "Buying Price",
    minStock: "Min Stock",
    checkout: "Checkout",
    total: "Total",
    discount: "Discount",
    grandTotal: "Grand Total",
    looseItem: "Loose Item (Decimal Qty)",
    addStockItem: "Add Stock Item",
    newBilling: "New Billing",
    searchProducts: "Search products...",
    cart: "Cart",
    emptyCart: "Cart is empty",
    checkoutDetails: "Checkout Details",
    expenseLog: "Expense Log",
    addNewExpense: "Add New Expense",
    expenseDesc: "Expense Description",
    expenseCategory: "Expense Category",
    allSystemsHealthy: "All Kirana store systems healthy",
    liveOperationalStatus: "Live operational status",
    restockItems: "Restock Items",
    lowStock: "Low Stock",
    goodStock: "Good Stock",

    // Toast and Dynamic Messaging
    addedToCart: "Added {name} to cart",
    billGenerated: "Bill generated! Paid ₹{total} via {method}",
    successfullyAddedToInventory: '"{name}" successfully added to inventory!',
    addedUnitsTo: "Added {qty} {unit} to {name}",
    allFieldsRequired: "All fields are required!",
    topSold: "Top Sold: {category}",
    noSalesToday: "No sales transactions recorded for this category today.",

    // Inventory & Stock Specific
    inventoryStock: "Inventory Stock",
    each: "each",
    weight: "Weight",
    units: "units",
    addNewInventoryItem: "Add New Inventory Item",
    productName: "Product Name",
    productNamePlaceholder: "e.g. Loose Chana Dal, Premium Basmati Rice...",
    openingStockKg: "Opening Stock (Kg)",
    openingStockQty: "Opening Stock (Qty)",
    soldLoose: "Sold Loose (Kg-based)",
    soldLooseHelp: "Toggle on for flour, grains, sugar sold by weight",
    buyingPriceKg: "Buying Price (₹ / Kg)",
    buyingPriceUnit: "Buying Price (₹ / Unit)",
    sellingPriceKg: "Selling Price (₹ / Kg)",
    sellingPriceUnit: "Selling Price (₹ / Unit)",
    addProductToInventory: "Add Product to Inventory",
    refillStock: "Refill Stock",
    currentInventoryLevel: "Current Inventory Level",
    inStockLabel: "{qty} {unit} in stock",
    qtyToAddLabel: "Quantity to Add ({unit})",
    quickPresets: "Quick Presets",
    confirmRefill: "Confirm Refill",

    // Shop Categories
    Grocery: "Grocery",
    Salon: "Salon",
    Pharmacy: "Pharmacy",
    Clothing: "Clothing",
    Electronics: "Electronics",
    General: "General",

    // Subcategories (Mock Inventory Groups)
    Groceries: "Groceries",
    "Packaged Food": "Packaged Food",
    Detergents: "Detergents",
    "Personal Care": "Personal Care",
    Cleaning: "Cleaning",
    Medicines: "Medicines",
    Diagnostics: "Diagnostics",
    Wellness: "Wellness",
    "Personal Hygiene": "Personal Hygiene",
    "Baby Care": "Baby Care",
    Slippers: "Slippers",
    "Sports Shoes": "Sports Shoes",
    Sandals: "Sandals",
    "Formal Shoes": "Formal Shoes",
    Socks: "Socks",
    Starters: "Starters",
    "Main Course": "Main Course",
    Biryani: "Biryani",
    Breads: "Breads",
    Beverages: "Beverages",
    Desserts: "Desserts",
    Notebooks: "Notebooks",
    "Pens & Pencils": "Pens & Pencils",
    "Art Supplies": "Art Supplies",
    Adhesives: "Adhesives",
    "Office Files": "Office Files",
    "Geometry Boxes": "Geometry Boxes",
    Vegetables: "Vegetables",
    "Fresh Fruits": "Fresh Fruits",
    "Leafy Greens": "Leafy Greens",
    Kitchenware: "Kitchenware",
    "Daily Utilities": "Daily Utilities",
    Toys: "Toys",
    Cosmetics: "Cosmetics",
    Biscuits: "Biscuits",

    // Products (Mock Inventory Items)
    Milk: "Milk",
    Bread: "Bread",
    Eggs: "Eggs",
    Rice: "Rice",
    Wheat: "Wheat",
    Oil: "Oil",
    Sugar: "Sugar",
    Salt: "Salt",
    Tea: "Tea",
    Coffee: "Coffee",
    Soap: "Soap",
    Shampoo: "Shampoo",
    Toothpaste: "Toothpaste",
    Biscuit: "Biscuit",
    Banana: "Banana",
    Apple: "Apple",

    // Medical/Pharmacy Mock items
    "Paracetamol 650mg": "Paracetamol 650mg",
    "Cough Syrup 100ml": "Cough Syrup 100ml",
    "Band-Aid Strips (Box)": "Band-Aid Strips (Box)",
    "Vitamin C 500mg": "Vitamin C 500mg",
    "N95 Face Mask": "N95 Face Mask",
    "Baby Wipes 80s": "Baby Wipes 80s",
    "Antiseptic Liquid 250ml": "Antiseptic Liquid 250ml",
    "Thermometer Digital": "Thermometer Digital",

    // Footwear Mock items
    "Bata Flip-Flops": "Bata Flip-Flops",
    "Running Sneakers": "Running Sneakers",
    "Leather Sandals": "Leather Sandals",
    "Formal Black Shoes": "Formal Black Shoes",
    "Cotton Socks (Pack of 3)": "Cotton Socks (Pack of 3)",
    "Casual Canvas Shoes": "Casual Canvas Shoes",
    "Kid's Velcro Sandals": "Kid's Velcro Sandals",
    "Soft Slippers (Indoor)": "Soft Slippers (Indoor)",

    // Restaurant Mock items
    "Paneer Tikka Double": "Paneer Tikka Double",
    "Butter Chicken Masala": "Butter Chicken Masala",
    "Hyderabadi Chicken Biryani": "Hyderabadi Chicken Biryani",
    "Garlic Butter Naan": "Garlic Butter Naan",
    "Fresh Mango Lassi": "Fresh Mango Lassi",
    "Gulab Jamun (2 Pcs)": "Gulab Jamun (2 Pcs)",
    "Paneer Butter Masala": "Paneer Butter Masala",
    "Jeera Rice Half": "Jeera Rice Half",

    // Stationery Mock items
    "Classmate Notebook A4": "Classmate Notebook A4",
    "Parker Vector Roller Pen": "Parker Vector Roller Pen",
    "Reynolds Ball Pen Blue": "Reynolds Ball Pen Blue",
    "Camel Water Colors Kit": "Camel Water Colors Kit",
    "Fevicol MR Squeeze 100g": "Fevicol MR Squeeze 100g",
    "Nataraj Pencil Box (10s)": "Nataraj Pencil Box (10s)",
    "A4 Printing Paper Ream": "A4 Printing Paper Ream",
    "Camlin Geometry Box": "Camlin Geometry Box",

    // Vegetables & Fruits Mock items
    "Fresh Potatoes (per Kg)": "Fresh Potatoes (per Kg)",
    "Onions Nasik (per Kg)": "Onions Nasik (per Kg)",
    "Tomatoes Hybrid (per Kg)": "Tomatoes Hybrid (per Kg)",
    "Shimla Apple (per Kg)": "Shimla Apple (per Kg)",
    "Cavendish Bananas (Dozen)": "Cavendish Bananas (Dozen)",
    "Fresh Spinach (Bunch)": "Fresh Spinach (Bunch)",
    "Alphonso Mangoes (per Kg)": "Alphonso Mangoes (per Kg)",
    "Green Coriander (Bunch)": "Green Coriander (Bunch)",

    // General Store Mock items
    "Ceramic Coffee Mug Blue": "Ceramic Coffee Mug Blue",
    "Plastic Water Bottle 1L": "Plastic Water Bottle 1L",
    "Barbie Fashion Doll": "Barbie Fashion Doll",
    "Hot Wheels Diecast Car": "Hot Wheels Diecast Car",
    "Stainless Steel Spoon Set": "Stainless Steel Spoon Set",
    "Lakme Eyeconic Kajal": "Lakme Eyeconic Kajal",
    "Nivea Cream Tub 100ml": "Nivea Cream Tub 100ml",
    "Syska LED Bulb 9W": "Syska LED Bulb 9W",

    // Grocery Mock items
    "Parle-G Biscuit": "Parle-G Biscuit",
    "Tata Salt 1kg": "Tata Salt 1kg",
    "Surf Excel 500g": "Surf Excel 500g",
    "Maggi Noodles": "Maggi Noodles",
    "Colgate 150g": "Colgate 150g",
    "Aashirvaad Atta 5kg": "Aashirvaad Atta 5kg",
    "Tata Tea 250g": "Tata Tea 250g",
    "Vim Bar": "Vim Bar"
  },
  ta: {
    // Admin Console
    adminController: "நிர்வாகி கட்டுப்பாட்டு மையம்",
    activeTenants: "செயலில் உள்ள கடைகள்",
    expiredAccounts: "காலாவதியான கணக்குகள்",
    totalRevenue: "மொத்த வருவாய்",
    manageShops: "கடைகளை நிர்வகி",
    analysis: "பகுப்பாய்வு",
    shopName: "கடை பெயர்",
    ownerName: "உரிமையாளர் பெயர்",
    username: "பயனர் பெயர்",
    password: "கடவுச்சொல்",
    plan: "திட்டம்",
    category: "வகை",
    provisionAccount: "கணக்கை உருவாக்கு",
    storeSubscriptions: "கடை சந்தாக்கள்",
    createStoreAccount: "புதிய கடை கணக்கு உருவாக்கு",
    manageCategories: "கடை வகைகளை நிர்வகி",
    addCustomCategory: "விருப்பப்படியான வகை சேர்",

    // Navigation & Tabs
    home: "முகப்பு",
    billing: "பில்லிங்",
    stock: "சரக்கு இருப்பு",
    expenses: "செலவுகள்",
    reports: "அறிக்கைகள்",
    logout: "வெளியேறு",

    // Merchant Dashboard Metrics
    totalSales: "மொத்த விற்பனை",
    netProfit: "நிகர லாபம்",
    itemsSold: "விற்கப்பட்டவை",
    customersVisited: "வருகை தந்தவர்கள்",

    // Common UI Labels & Actions
    quickActions: "விரைவுச் செயல்கள்",
    recentBills: "சமீபத்திய பில்கள்",
    addStock: "சரக்கு சேர்",
    addExpense: "செலவு சேர்",
    billingCheckout: "பில்லிங் & செக்அவுட்",
    expired: "காலாவதியானது",
    active: "செயலில் உள்ளது",
    expiresIn: "காலாவதியாகும் காலம்",
    viewPricing: "கட்டண விவரங்கள் & சந்தா",
    days: "நாட்கள்",
    day: "நாள்",
    expiredPlanWarning: "உங்கள் சந்தா காலாவதியாகிவிட்டது! தயவுசெய்து புதுப்பிக்கவும்.",
    expirationWarning: "உங்கள் திட்டம் {days} நாட்களில் காலாவதியாகிறது!",
    renewNow: "இப்போது புதுப்பி",
    recentTransactions: "சமீபத்திய பரிவர்த்தனைகள்",
    paymentMethod: "பணம் செலுத்தும் முறை",
    CASH: "பணம் (Cash)",
    UPI: "UPI",
    CARD: "அட்டை (Card)",
    cash: "பணம் (Cash)",
    upi: "UPI",
    card: "அட்டை (Card)",
    amount: "தொகை",
    description: "விளக்கம்",
    save: "சேமி",
    cancel: "ரத்து செய்",
    search: "தேடு",
    qty: "அளவு",
    price: "விற்பனை விலை",
    buyingPrice: "கொள்முதல் விலை",
    minStock: "குறைந்தபட்ச இருப்பு",
    checkout: "செக்அவுட்",
    total: "மொத்தம்",
    discount: "தள்ளுபடி",
    grandTotal: "நிகர மொத்தம்",
    looseItem: "உதிரிப் பொருள் (Loose)",
    addStockItem: "புதிய பொருள் சேர்",
    newBilling: "புதிய பில்லிங்",
    searchProducts: "பொருட்களை தேடு...",
    cart: "கூடை (Cart)",
    emptyCart: "கூடை காலியாக உள்ளது",
    checkoutDetails: "செக்அவுட் விவரங்கள்",
    expenseLog: "செலவு பதிவேடு",
    addNewExpense: "புதிய செலவை பதிவுசெய்",
    expenseDesc: "செலவு விவரம்",
    expenseCategory: "செலவு வகை",
    allSystemsHealthy: "அனைத்து அமைப்புகளும் சீராக உள்ளன",
    liveOperationalStatus: "நேரடி செயல்பாட்டு நிலை",
    restockItems: "சரக்கு கூட்டு",
    lowStock: "குறைந்த இருப்பு",
    goodStock: "போதுமான இருப்பு",

    // Toast and Dynamic Messaging
    addedToCart: "{name} கூடையில் சேர்க்கப்பட்டது",
    billGenerated: "பில் உருவாக்கப்பட்டது! {method} மூலம் ₹{total} செலுத்தப்பட்டது",
    successfullyAddedToInventory: '"{name}" வெற்றிகரமாக சரக்கில் சேர்க்கப்பட்டது!',
    addedUnitsTo: "{name} இல் {qty} {unit} சேர்க்கப்பட்டது",
    allFieldsRequired: "அனைத்து துறைகளும் கட்டாயமாகும்!",
    topSold: "அதிக விற்பனை: {category}",
    noSalesToday: "இந்த பிரிவில் இன்று எந்த விற்பனை பரிவர்த்தனைகளும் இல்லை.",

    // Inventory & Stock Specific
    inventoryStock: "சரக்கு இருப்பு விவரம்",
    each: "ஒன்று",
    weight: "எடை",
    units: "அலகுகள்",
    addNewInventoryItem: "புதிய சரக்கு பொருள் சேர்",
    productName: "பொருள் பெயர்",
    productNamePlaceholder: "உதாரணம்: உளுந்தம் பருப்பு, பாஸ்மதி அரிசி...",
    openingStockKg: "துவக்க இருப்பு (கிலோ)",
    openingStockQty: "துவக்க இருப்பு (அளவு)",
    soldLoose: "உதிரியாக விற்பனை (கிலோ)",
    soldLooseHelp: "மாவு, தானியங்கள், சர்க்கரை போன்றவற்றிற்கு இயக்கவும்",
    buyingPriceKg: "கொள்முதல் விலை (₹ / கிலோ)",
    buyingPriceUnit: "கொள்முதல் விலை (₹ / அலகு)",
    sellingPriceKg: "விற்பனை விலை (₹ / கிலோ)",
    sellingPriceUnit: "விற்பனை விலை (₹ / அலகு)",
    addProductToInventory: "பொருளை சரக்கில் சேர்",
    refillStock: "சரக்கு கூட்டு",
    currentInventoryLevel: "தற்போதைய இருப்பு நிலை",
    inStockLabel: "{qty} {unit} இருப்பில் உள்ளது",
    qtyToAddLabel: "சேர்க்க வேண்டிய அளவு ({unit})",
    quickPresets: "விரைவு அளவுகள்",
    confirmRefill: "புதுப்பிப்பை உறுதிசெய்",

    // Shop Categories
    Grocery: "மளிகை",
    Salon: "சலூன்",
    Pharmacy: "மருந்தகம்",
    Clothing: "துணிக்கடை",
    Electronics: "மின்னணுவியல்",
    General: "பொதுவானது",

    // Subcategories (Mock Inventory Groups)
    Groceries: "மளிகைப் பொருட்கள்",
    "Packaged Food": "பேக் செய்யப்பட்ட உணவுகள்",
    Detergents: "சலவை தூள்",
    "Personal Care": "தனிநபர் பராமரிப்பு",
    Cleaning: "சுத்தம் செய்தல்",
    Medicines: "மருந்துகள்",
    Diagnostics: "கண்டறிதல்",
    Wellness: "நலவாழ்வு",
    "Personal Hygiene": "தனிநபர் சுகாதாரம்",
    "Baby Care": "குழந்தை பராமரிப்பு",
    Slippers: "செருப்புகள்",
    "Sports Shoes": "விளையாட்டு காலணிகள்",
    Sandals: "சாண்டல்கள்",
    "Formal Shoes": "முறைசார் காலணிகள்",
    Socks: "காலுறைகள்",
    Starters: "துவக்க உணவுகள்",
    "Main Course": "முதன்மை உணவுகள்",
    Biryani: "பிரியாணி",
    Breads: "ரொட்டி வகைகள்",
    Beverages: "பானங்கள்",
    Desserts: "இனிப்பு வகைகள்",
    Notebooks: "நோட்டுப் புத்தகங்கள்",
    "Pens & Pencils": "பேனாக்கள் மற்றும் பென்சில்கள்",
    "Art Supplies": "ஓவியப் பொருட்கள்",
    Adhesives: "பசைகள்",
    "Office Files": "அலுவலக கோப்புகள்",
    "Geometry Boxes": "வடிவியல் பெட்டிகள்",
    Vegetables: "காய்கறிகள்",
    "Fresh Fruits": "புதிய பழங்கள்",
    "Leafy Greens": "கீரைகள்",
    Kitchenware: "சமையலறைப் பொருட்கள்",
    "Daily Utilities": "தினசரி பயன்பாடுகள்",
    Toys: "பொம்மைகள்",
    Cosmetics: "அழகு சாதனங்கள்",
    Biscuits: "பிஸ்கட்",

    // Products (Mock Inventory Items)
    Milk: "பால்",
    Bread: "ரொட்டி",
    Eggs: "முட்டை",
    Rice: "அரிசி",
    Wheat: "கோதுமை",
    Oil: "எண்ணெய்",
    Sugar: "சர்க்கரை",
    Salt: "உப்பு",
    Tea: "தேநீர்",
    Coffee: "காபி",
    Soap: "சோப்பு",
    Shampoo: "ஷாம்பு",
    Toothpaste: "பற்பசை",
    Biscuit: "பிஸ்கட்",
    Banana: "வாழைப்பழம்",
    Apple: "ஆப்பிள்",

    // Medical/Pharmacy Mock items
    "Paracetamol 650mg": "பாராசிட்டமால் 650mg",
    "Cough Syrup 100ml": "இருமல் மருந்து 100ml",
    "Band-Aid Strips (Box)": "பான்ட்-எய்ட் (பெட்டி)",
    "Vitamin C 500mg": "வைட்டமின் சி 500mg",
    "N95 Face Mask": "N95 முகக்கவசம்",
    "Baby Wipes 80s": "குழந்தை துடைப்பான்கள் 80s",
    "Antiseptic Liquid 250ml": "கிருமிநாசினி திரவம் 250ml",
    "Thermometer Digital": "டிஜிட்டல் வெப்பமானி",

    // Footwear Mock items
    "Bata Flip-Flops": "பட்டா செருப்புகள்",
    "Running Sneakers": "ஓட்டப் காலணிகள்",
    "Leather Sandals": "தோல் சாண்டல்கள்",
    "Formal Black Shoes": "முறைசார் கருப்பு காலணிகள்",
    "Cotton Socks (Pack of 3)": "பருத்தி காலுறைகள் (3 ஜோடி)",
    "Casual Canvas Shoes": "கேஷுவல் காலணிகள்",
    "Kid's Velcro Sandals": "குழந்தைகளுக்கான சாண்டல்கள்",
    "Soft Slippers (Indoor)": "மென்மையான வீட்டு செருப்புகள்",

    // Restaurant Mock items
    "Paneer Tikka Double": "பன்னீர் டிக்கா டபுள்",
    "Butter Chicken Masala": "பட்டர் சிக்கன் மசாலா",
    "Hyderabadi Chicken Biryani": "ஹைதராபாத் சிக்கன் பிரியாணி",
    "Garlic Butter Naan": "பூண்டு வெண்ணெய் நான்",
    "Fresh Mango Lassi": "புதிய மாம்பழ லஸ்ஸி",
    "Gulab Jamun (2 Pcs)": "குலாப் ஜாமூன் (2 துண்டுகள்)",
    "Paneer Butter Masala": "பன்னீர் பட்டர் மசாலா",
    "Jeera Rice Half": "சீரக சாதம் அரை",

    // Stationery Mock items
    "Classmate Notebook A4": "கிளாஸ்மேட் நோட்டு A4",
    "Parker Vector Roller Pen": "பார்க்கர் பேனா",
    "Reynolds Ball Pen Blue": "ரெனால்ட்ஸ் நீல பேனா",
    "Camel Water Colors Kit": "கேமல் நீர் வண்ணங்கள்",
    "Fevicol MR Squeeze 100g": "ஃபெவிகால் 100g",
    "Nataraj Pencil Box (10s)": "நடராஜ் பென்சில் பெட்டி (10 எண்ணிக்கை)",
    "A4 Printing Paper Ream": "A4 அச்சு காகிதம்",
    "Camlin Geometry Box": "கேம்லின் வடிவியல் பெட்டி",

    // Vegetables & Fruits Mock items
    "Fresh Potatoes (per Kg)": "புதிய உருளைக்கிழங்கு (ஒரு கிலோ)",
    "Onions Nasik (per Kg)": "நாசிக் வெங்காயம் (ஒரு கிலோ)",
    "Tomatoes Hybrid (per Kg)": "தக்காளி ஹைப்ரிட் (ஒரு கிலோ)",
    "Shimla Apple (per Kg)": "சிம்லா ஆப்பிள் (ஒரு கிலோ)",
    "Cavendish Bananas (Dozen)": "வாழைப்பழம் (ஒரு டஜன்)",
    "Fresh Spinach (Bunch)": "புதிய கீரை (கட்டு)",
    "Alphonso Mangoes (per Kg)": "அல்போன்சா மாம்பழம் (ஒரு கிலோ)",
    "Green Coriander (Bunch)": "கொத்தமல்லி (கட்டு)",

    // General Store Mock items
    "Ceramic Coffee Mug Blue": "செராமிக் காபி கப் நீலம்",
    "Plastic Water Bottle 1L": "பிளாஸ்டிக் தண்ணீர் பாட்டில் 1L",
    "Barbie Fashion Doll": "பார்பி பொம்மை",
    "Hot Wheels Diecast Car": "ஹாட் வீல்ஸ் பொம்மை கார்",
    "Stainless Steel Spoon Set": "துруப்பிடிக்காத எஃகு ஸ்பூன் செட்",
    "Lakme Eyeconic Kajal": "லாக்மே காஜல்",
    "Nivea Cream Tub 100ml": "நிவியா கிரீம் 100ml",
    "Syska LED Bulb 9W": "சிஸ்கா எல்இடி பல்பு 9W",

    // Grocery Mock items
    "Parle-G Biscuit": "பார்லே-ஜி பிஸ்கட்",
    "Tata Salt 1kg": "டாட்டா உப்பு 1 கிலோ",
    "Surf Excel 500g": "சர்ப் எக்செல் 500 கிராம்",
    "Maggi Noodles": "மேகி நூடுல்ஸ்",
    "Colgate 150g": "கோல்கேட் 150 கிராம்",
    "Aashirvaad Atta 5kg": "ஆசிர்வாத் கோதுமை மாவு 5 கிலோ",
    "Tata Tea 250g": "டாட்டா தேநீர் 250 கிராம்",
    "Vim Bar": "விம் பார்"
  },
  ur: {
    // Admin Console
    adminController: "ایڈمن کنٹرولر",
    activeTenants: "فعال دکانیں",
    expiredAccounts: "غیر فعال دکانیں",
    totalRevenue: "کل آمدنی",
    manageShops: "دکانوں کا انتظام",
    analysis: "تجزیہ",
    shopName: "دکان کا نام",
    ownerName: "مالک کا نام",
    username: "یوزر نیم",
    password: "پاس ورڈ",
    plan: "پلان",
    category: "کیٹیگری",
    provisionAccount: "اکاؤنٹ بنائیں",
    storeSubscriptions: "دکانوں کی سبسکرپشن",
    createStoreAccount: "نیا دکان اکاؤنٹ بنائیں",
    manageCategories: "دکان کی کیٹیگریز",
    addCustomCategory: "کیٹیگری شامل کریں",

    // Navigation & Tabs
    home: "ہوم",
    billing: "بلنگ",
    stock: "سٹاک",
    expenses: "اخراجات",
    reports: "رپورٹس",
    logout: "لاگ آؤٹ",

    // Merchant Dashboard Metrics
    totalSales: "کل فروخت",
    netProfit: "کل منافع",
    itemsSold: "فروخت شدہ اشیاء",
    customersVisited: "گاہکوں کی آمد",

    // Common UI Labels & Actions
    quickActions: "فوری کام",
    recentBills: "حالیہ بلز",
    addStock: "سٹاک شامل کریں",
    addExpense: "خرچہ لکھیں",
    billingCheckout: "بلنگ اور چیک آؤٹ",
    expired: "ختم شدہ",
    active: "فعال",
    expiresIn: "باقی وقت",
    viewPricing: "پلان اور سبسکرپشن دیکھیں",
    days: "دن",
    day: "دن",
    expiredPlanWarning: "آپ کا سبسکرپشن ختم ہو گیا ہے! براہ کرم رینیو کریں۔",
    expirationWarning: "آپ کا پلان {days} دن میں ختم ہو جائے گا!",
    renewNow: "ابھی رینیو کریں",
    recentTransactions: "حالیہ لین دین",
    paymentMethod: "ادائیگی کا طریقہ",
    CASH: "نقد (Cash)",
    UPI: "UPI",
    CARD: "کارڈ (Card)",
    cash: "نقد (Cash)",
    upi: "UPI",
    card: "کارڈ (Card)",
    amount: "رقم",
    description: "تفصیل",
    save: "save / محفوظ",
    cancel: "منسوخ کریں",
    search: "تلاش کریں",
    qty: "تعداد",
    price: "فروخت کی قیمت",
    buyingPrice: "خریداری کی قیمت",
    minStock: "کم از کم سٹاک",
    checkout: "چیک آؤٹ",
    total: "کل",
    discount: "رعایت",
    grandTotal: "کل رقم",
    looseItem: "کھلی چیز (Loose)",
    addStockItem: "سٹاک میں چیز شامل کریں",
    newBilling: "نئی بلنگ",
    searchProducts: "اشیاء تلاش کریں...",
    cart: "کارٹ",
    emptyCart: "کارٹ خالی ہے",
    checkoutDetails: "چیک آؤٹ تفصیلات",
    expenseLog: "اخراجات کا ریکارڈ",
    addNewExpense: "نیا خرچہ لکھیں",
    expenseDesc: "خرچے کی تفصیل",
    expenseCategory: "خرچے کی قسم",
    allSystemsHealthy: "سارے سسٹم ٹھیک کام کر رہے ہیں",
    liveOperationalStatus: "لائیو آپریشنل حالت",
    restockItems: "سٹاک بڑھائیں",
    lowStock: "کم سٹاک",
    goodStock: "سٹاک ٹھیک ہے",

    // Toast and Dynamic Messaging
    addedToCart: "{name} کارٹ میں شامل کر دیا گیا",
    billGenerated: "بل بن گیا! {method} کے ذریعے ₹{total} ادا کیے گئے",
    successfullyAddedToInventory: '"{name}" کامیابی کے ساتھ سٹاک میں شامل ہو گیا!',
    addedUnitsTo: "{name} میں {qty} {unit} شامل کر دیا گیا",
    allFieldsRequired: "تمام خانے پر کرنا لازمی ہے!",
    topSold: "سب سے زیادہ فروخت: {category}",
    noSalesToday: "آج اس کیٹیگری میں کوئی فروخت ریکارڈ نہیں ہوئی۔",

    // Inventory & Stock Specific
    inventoryStock: "انوینٹری سٹاک",
    each: "فی عدد",
    weight: "وزن",
    units: "یونٹس",
    addNewInventoryItem: "سٹاک میں نئی چیز شامل کریں",
    productName: "پروڈکٹ کا نام",
    productNamePlaceholder: "مثلاً: چنے کی دال، باسمتی چاول...",
    openingStockKg: "افتتاحی سٹاک (کلو)",
    openingStockQty: "افتتاحی سٹاک (تعداد)",
    soldLoose: "کھلی فروخت (کلوگرام کی بنیاد پر)",
    soldLooseHelp: "آٹا، اناج، چینی وغیرہ کے لیے آن کریں",
    buyingPriceKg: "خریداری کی قیمت (₹ / کلو)",
    buyingPriceUnit: "خریداری کی قیمت (₹ / یونٹ)",
    sellingPriceKg: "فروخت کی قیمت (₹ / کلو)",
    sellingPriceUnit: "فروخت کی قیمت (₹ / یونٹ)",
    addProductToInventory: "پروڈکٹ سٹاک میں شامل کریں",
    refillStock: "سٹاک بڑھائیں",
    currentInventoryLevel: "سٹاک کی موجودہ صورتحال",
    inStockLabel: "{qty} {unit} سٹاک میں موجود ہے",
    qtyToAddLabel: "شامل کرنے کی مقدار ({unit})",
    quickPresets: "فوری تعداد",
    confirmRefill: "سٹاک بڑھانے کی تصدیق کریں",

    // Shop Categories
    Grocery: "گروسری / کریانہ",
    Salon: "سیلون",
    Pharmacy: "فارمیسی / میڈیکل",
    Clothing: "کپڑے",
    Electronics: "الیکٹرانکس",
    General: "عام",

    // Subcategories (Mock Inventory Groups)
    Groceries: "کریانہ کی اشیاء",
    "Packaged Food": "پیک شدہ کھانا",
    Detergents: "سرف",
    "Personal Care": "ذاتی نگہداشت",
    Cleaning: "صفائی کا سامان",
    Medicines: "ادویات",
    Diagnostics: "تشخیص",
    Wellness: "صحت و تندرستی",
    "Personal Hygiene": "ذاتی صفائی",
    "Baby Care": "بچوں کی دیکھ بھال",
    Slippers: "چپلیں",
    "Sports Shoes": "اسپورٹس جوتے",
    Sandals: "سینڈل",
    "Formal Shoes": "رسمی جوتے",
    Socks: "جرابیں",
    Starters: "سٹارٹرز",
    "Main Course": "مین کورس",
    Biryani: "بریانی",
    Breads: "روٹی / نان",
    Beverages: "مشروبات",
    Desserts: "میٹھی اشیاء",
    Notebooks: "کاپیاں",
    "Pens & Pencils": "قلم اور پنسلیں",
    "Art Supplies": "آرٹ کا سامان",
    Adhesives: "گوند / الفی",
    "Office Files": "دفتر کی فائلیں",
    "Geometry Boxes": "جیومیٹری بکس",
    Vegetables: "سبزیاں",
    "Fresh Fruits": "تازہ پھل",
    "Leafy Greens": "پتوں والی سبزیاں",
    Kitchenware: "برتن",
    "Daily Utilities": "روزمرہ کی چیزیں",
    Toys: "کھلونے",
    Cosmetics: "کاسمیٹکس / میک اپ",
    Biscuits: "بسکٹ",

    // Products (Mock Inventory Items)
    Milk: "دودھ",
    Bread: "ڈبل روٹی",
    Eggs: "انڈے",
    Rice: "چاول",
    Wheat: "گندم",
    Oil: "تیل",
    Sugar: "چینی",
    Salt: "نمک",
    Tea: "چائے",
    Coffee: "کافی",
    Soap: "صابن",
    Shampoo: "شیمپو",
    Toothpaste: "ٹوتھ پیسٹ",
    Biscuit: "بسکٹ",
    Banana: "کیلا",
    Apple: "سیب",

    // Medical/Pharmacy Mock items
    "Paracetamol 650mg": "پیراسیٹامول 650 ملی گرام",
    "Cough Syrup 100ml": "کھانسی کا شربت 100 ملی لیٹر",
    "Band-Aid Strips (Box)": "بینڈ ایڈ پٹی (ڈبہ)",
    "Vitamin C 500mg": "وٹامن سی 500 ملی گرام",
    "N95 Face Mask": "این 95 فیس ماسک",
    "Baby Wipes 80s": "بیبی وائپس 80s",
    "Antiseptic Liquid 250ml": "اینٹی سیپٹک مائع 250 ملی لیٹر",
    "Thermometer Digital": "ڈیجیٹل تھرمامیٹر",

    // Footwear Mock items
    "Bata Flip-Flops": "باٹا چپل",
    "Running Sneakers": "جوتے دوڑنے والے",
    "Leather Sandals": "چرمی سینڈل",
    "Formal Black Shoes": "رسمی کالے جوتے",
    "Cotton Socks (Pack of 3)": "سوتی جرابیں (3 کا پیکٹ)",
    "Casual Canvas Shoes": "کیژول جوتے",
    "Kid's Velcro Sandals": "بچوں کے سینڈل",
    "Soft Slippers (Indoor)": "نرم چپل (انڈور)",

    // Restaurant Mock items
    "Paneer Tikka Double": "پنیر تکہ ڈبل",
    "Butter Chicken Masala": "بٹر چکن مصالحہ",
    "Hyderabadi Chicken Biryani": "حیدرآبادی چکن بریانی",
    "Garlic Butter Naan": "لہسن مکھن نان",
    "Fresh Mango Lassi": "تازہ آم کی لسی",
    "Gulab Jamun (2 Pcs)": "گلاب جامن (2 عدد)",
    "Paneer Butter Masala": "پنیر بٹر مصالحہ",
    "Jeera Rice Half": "زیرہ والے چاول ہاف",

    // Stationery Mock items
    "Classmate Notebook A4": "کلاسمیٹ کاپی A4",
    "Parker Vector Roller Pen": "پارکر قلم",
    "Reynolds Ball Pen Blue": "رینالڈز نیلا بال پین",
    "Camel Water Colors Kit": "کیمل واٹر کلر کٹ",
    "Fevicol MR Squeeze 100g": "فیویکول 100 گرام",
    "Nataraj Pencil Box (10s)": "نٹراج پنسل ڈبہ (10 پنسلیں)",
    "A4 Printing Paper Ream": "پرنٹنگ کا کاغذ A4 ریم",
    "Camlin Geometry Box": "کیملن جیومیٹری بکس",

    // Vegetables & Fruits Mock items
    "Fresh Potatoes (per Kg)": "تازہ آلو (فی کلو)",
    "Onions Nasik (per Kg)": "پیاز ناسک (فی کلو)",
    "Tomatoes Hybrid (per Kg)": "ٹماٹر ہائبرڈ (فی کلو)",
    "Shimla Apple (per Kg)": "شملہ سیب (فی کلو)",
    "Cavendish Bananas (Dozen)": "کیلے (درجن)",
    "Fresh Spinach (Bunch)": "تازہ پالک (گٹھی)",
    "Alphonso Mangoes (per Kg)": "الفانسو آم (فی کلو)",
    "Green Coriander (Bunch)": "ہرا دھنیا (گٹھی)",

    // General Store Mock items
    "Ceramic Coffee Mug Blue": "سیرامک کافی مگ نیلا",
    "Plastic Water Bottle 1L": "پلاسٹک پانی کی بوتل 1 لیٹر",
    "Barbie Fashion Doll": "باربی ڈول",
    "Hot Wheels Diecast Car": "ہٹ ویلز کھلونا کار",
    "Stainless Steel Spoon Set": "اسٹیل کے چمچوں کا سیٹ",
    "Lakme Eyeconic Kajal": "لیکمے کاجل",
    "Nivea Cream Tub 100ml": "نیویا کریم 100 ملی لیٹر",
    "Syska LED Bulb 9W": "سسکا ایل ای ڈی بلب 9 واٹ",

    // Grocery Mock items
    "Parle-G Biscuit": "پارلے جی بسکٹ",
    "Tata Salt 1kg": "ٹاٹا نمک 1 کلو",
    "Surf Excel 500g": "سرف ایکسل 500 گرام",
    "Maggi Noodles": "میگی نوڈلز",
    "Colgate 150g": "کولگیٹ 150 گرام",
    "Aashirvaad Atta 5kg": "آشیرواد آٹا 5 کلو",
    "Tata Tea 250g": "ٹاٹا چائے 250 گرام",
    "Vim Bar": "وِم بار"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('apna_khata_lang') || 'en';
  });

  const t = (key, replacements = {}) => {
    // Clean key and fallback to exact key if not found
    const trimmedKey = String(key || '').trim();
    let text = dictionary[language]?.[trimmedKey] || dictionary['en']?.[trimmedKey] || trimmedKey;
    
    // Support basic template replacements like {days}
    Object.entries(replacements).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });
    
    return text;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('apna_khata_lang', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
